replicaCount: 1

image:
  repository: ghcr.io/jha-hitesh/slack-channels-proxy
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: slack-proxy.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

containerPort: 8000

env:
  appEnv: local
  appHost: 0.0.0.0
  appPort: "8000"
  docsUsername: admin
  docsPassword: admin
  slackBaseUrl: https://slack.com/api
  databaseUrl: sqlite:///./data/slack_proxy.db
  syncLockStaleAfterMinutes: "10"

persistence:
  enabled: true
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  size: 1Gi
  mountPath: /app/data
